Repository OpenVoxProject/openvox-server, pull requests merged in 2025-07, with the labels that each got.

#32 Remove legacy CODEOWNERS
  CODEOWNERS
Labels: skip-changelog

#49 public_suffix: Allow newer versions
  Gemfile
Labels: skip-changelog

#51 Delete legacy Perforce/Jenkins leftovers
  Rakefile
  project.clj
Labels: skip-changelog

#52 Release 8.9.0
  CHANGELOG.md
  Gemfile
  Rakefile
  project.clj
Labels: skip-changelog

#54 chore: update rexml to 3.4.1
  resources/ext/build-scripts/jruby-stdlib-gem-list.txt
Labels: enhancement, ruby

#55 (ci) Use shared_actions/.github/workflows/beaker_acceptance.yml
  .github/workflows/acceptance.yml
Labels: skip-changelog

#56 CI: Add token permissions to build workflow & Add ezbake-ref option to build pipeline
  .github/workflows/build.yml
Labels: skip-changelog

#57 Run tests on JRE11, 17 & 21 (21 without FIPS)
  .github/workflows/pr-testing.yml
  project.clj
Labels: enhancement

#62 Consider Java 21 "supported"
  .github/workflows/pr-testing.yml
  project.clj
  resources/ext/cli_defaults/cli-defaults.sh.erb
  src/clj/puppetlabs/services/master/master_service.clj
  test/unit/puppetlabs/services/master/master_core_test.clj
Labels: enhancement

#58 depend on openvox-agent 8.21.1 or newer
  resources/ext/ezbake.conf
Labels: enhancement

#65 Release 8.10.0
  .github/workflows/release.yaml
  CHANGELOG.md
  project.clj
Labels: skip-changelog
